spring:
  application:
    name: pensacare
  datasource:
    url: "jdbc:postgresql://localhost:5432/pensacare"
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    property-naming-strategy: SNAKE_CASE
#    show-sql: true
jwt:
  secret: "d98154217015a9805e3695d91f393bbb63e29661b3cfa33e69f26ada2bbc43d4cab2be9ac355ffabec0f8b934ffbe6fe8dead9b0b0beec9f743f15c445d128e3"
  expires: 720

pensacare:
  create-default-user: true
  default-username: admin
  default-password: pensacare